apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
        - name: springapp-container
          image: thedevroom/spring-boot-mongo-application:1
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_DB_HOSTNAME
              value: db-service
            - name: MONGO_DB_USERNAME
              value: dbuser
            - name: MONGO_DB_PASSWORD
              value: dbadmin@123
---
apiVersion: v1
kind: Service
metadata:
  name: springapp-service
  namespace: app
spec:
  selector:
    app: springapp
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: dbuser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: dbadmin@123
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: app
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
