apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: <registry/image:tag>
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: dbuser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: dbadmin@123