apiVersion: v1
kind: Service
metadata:
  name: springapp-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: springapp
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort
