apiVersion: v1
kind: Service
metadata:
  name: springapp-service
  namespace: {{ include "springboot-mongo.namespace" . }}
  labels:
    app: springapp
    env: {{ .Values.environment }}
spec:
  selector:
    app: springapp
    env: {{ .Values.environment }}
  ports:
    - port: 80
      targetPort: {{ .Values.springapp.port }}
  type: NodePort
