apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: {{ include "springboot-mongo.namespace" . }}
  labels:
    app: mongo
    env: {{ .Values.environment }}
spec:
  selector:
    app: mongo
    env: {{ .Values.environment }}
  ports:
    - port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
