apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app

resources:
- ../../base

patches:
- path: patch/database.yaml
  target:
    group: apps
    kind: Deployment
    name: mongo
    version: v1
- path: patch/springapp.yaml
  target:
    group: apps
    kind: Deployment
    name: springapp
    version: v1
labels:
- includeSelectors: true
  pairs:
    application_type: demoApp
    managed_by: thedevroom
